import test from 'node:test';
import assert from 'node:assert/strict';
import {THEMES,QUESTIONS} from '../public/data.js';
import {INPUT,createGame,addPlayer,makeMap,makeLobby,startMap,enterLobby,tick,command,questionFor,geom,plateBounds,hurt,interact,normalizeAvatar,doorX,platformAt,beamFor,rayBox,snapshot,restoreSnapshot} from '../public/core.js';
const frame=(g,p,held=0,pressed=0)=>tick(g,{[p.id]:{held,pressed}},1/60);
function setup(id=0,two=false){const g=createGame(40),p=addPlayer(g,'alice','Alice');if(two)addPlayer(g,'bob','Bob');startMap(g,id);return{g,p,b:g.players[1]}}
function peaceful(g){g.enemies=[];g.map.hazards=[];g.relays.forEach(r=>r.open=true);g.routeProgress=g.map.platforms.length-1;g.optics.forEach(o=>o.solved=true)}
function objectives(g){g.fuses=g.fuses.map(()=>true);g.relays.forEach(r=>r.open=true);g.routeProgress=g.map.platforms.length-1;g.optics.forEach(o=>o.solved=true)}
function exit(g,p){p.x=g.map.exit.x+18;p.y=g.map.exit.y+g.map.exit.h-p.h;interact(g,p)}
function answerBoth(g,p){for(let i=0;i<2;i++){const q=questionFor(g,p);assert.equal(command(g,p,'answer',{choice:q.correct,nonce:q.nonce}),true)}}
test('40 authored scenarios have distinct topology and a selective mix of challenges',()=>{
 const maps=Array.from({length:40},(_,i)=>makeMap(i));assert.equal(new Set(maps.map(m=>JSON.stringify(m.platforms))).size,40);assert.equal(new Set(maps.map(m=>m.name)).size,40);
 for(const m of maps){assert.ok(m.route.length>=9);assert.ok(m.enemies.length>=2);assert.equal(m.fuses.length,3);assert.equal(m.relays.length,2);assert.ok(m.width>900&&m.height>900)}
 assert.equal(maps.filter(m=>m.slides.length).length,6);assert.ok(maps.filter(m=>m.platforms.some(p=>p.track)).length>=8);assert.ok(maps.some(m=>m.exit.x<m.spawn.x+200));assert.ok(maps.some(m=>m.spawn.y<m.exit.y));assert.ok(maps.some(m=>m.spawn.y>m.exit.y));assert.ok(maps[39].platforms[1].w<maps[0].platforms[1].w);
});
test('80 unique questions are assigned exactly once in a complete campaign',()=>{const seen=new Set();assert.equal(QUESTIONS.flat().length,80);for(let id=0;id<40;id++){const{g,p}=setup(id);for(let step=0;step<2;step++){p.quizStep=step;const q=questionFor(g,p);assert.ok(!seen.has(q.text));seen.add(q.text);assert.equal(q.options.length,4);assert.equal(new Set(q.options).size,4);assert.ok(q.correct>=0&&q.correct<4);assert.ok(q.explanation&&q.source)}}assert.equal(seen.size,80)});
test('Character Lab is reachable before Utility and saves a normalized appearance',()=>{const g=createGame(),p=addPlayer(g,'a','Alex');p.x=190;interact(g,p);assert.equal(p.interaction,'designer');command(g,p,'avatar',{name:'Custom Tech',avatar:{color:'#f493b0',helmet:'#85c6f3',shape:'round',face:'smile'}});assert.equal(p.avatar.shape,'round');assert.equal(p.name,'Custom Tech');assert.equal(normalizeAvatar({color:'bad'}).color,'#68d7ba');command(g,p,'close');p.x=doorX(1)+60;interact(g,p);assert.equal(p.interaction,null);p.x=doorX(0)+60;interact(g,p);assert.equal(p.interaction,'room:0')});
test('Every exit rejects missing objectives; wrong answers teleport to spawn and invalidate stale submissions',()=>{for(let id=0;id<40;id++){const{g,p}=setup(id);peaceful(g);exit(g,p);assert.equal(p.quiz,null);objectives(g);exit(g,p);assert.ok(p.quiz);const q=questionFor(g,p),wrong=(q.correct+1)%4;assert.equal(command(g,p,'answer',{choice:wrong,nonce:q.nonce}),false);assert.equal(p.x,g.map.spawn.x);assert.equal(p.y,g.map.spawn.y);assert.equal(p.safeX,g.map.spawn.x);assert.equal(p.quiz,null);assert.ok(g.fuses.every(Boolean));assert.ok(g.relays.every(r=>r.open));assert.equal(g.phase,'active');assert.equal(command(g,p,'answer',{choice:q.correct,nonce:q.nonce}),false)}});
test('Two correct equipment answers are required at every solo exit',()=>{const g=createGame(),p=addPlayer(g,'solo','Tech');for(let id=0;id<40;id++){assert.ok(startMap(g,id));objectives(g);exit(g,p);const q=questionFor(g,p);command(g,p,'answer',{choice:q.correct,nonce:q.nonce});assert.equal(g.phase,'active');assert.equal(p.quizStep,1);const q2=questionFor(g,p);assert.notEqual(q.index,q2.index);command(g,p,'answer',{choice:q2.correct,nonce:q2.nonce});assert.equal(g.phase,'clear');assert.equal(g.progress,id+1);if(id%5===4){assert.equal(g.story.playing,true,'room-completion scene starts without a next/play command');assert.equal(g.story.chapter,Math.floor(id/5)+1);command(g,p,'storySkip');assert.equal(g.mode,'lobby');assert.equal(p.x,doorX(Math.floor(id/5))+65)}}});
test('Co-op requires each teammate to answer at the exit; one player cannot finish remotely',()=>{const{g,p,b}=setup(0,true);objectives(g);exit(g,p);answerBoth(g,p);assert.equal(g.phase,'active');assert.equal(p.passed,true);assert.equal(b.passed,false);exit(g,b);answerBoth(g,b);assert.equal(g.phase,'clear')});
test('Solo relay uses timed latches; co-op requires different players at both pads',()=>{for(const two of [false,true]){const{g,p,b}=setup(0,two);g.enemies=[];g.map.hazards=[];let rel=g.relays[0],def=g.map.relays[0];function place(person,index){const a=plateBounds(g,def.plates[index]);person.x=a.x+10;person.y=a.y+10-person.h;person.grounded=true;person.vy=0}
 place(p,0);for(let i=0;i<3;i++)frame(g,p);assert.equal(rel.open,false);place(p,1);if(two){for(let i=0;i<50;i++)frame(g,p);assert.equal(rel.open,false);place(b,0)}for(let i=0;i<45;i++)tick(g,{},1/60);assert.equal(rel.open,true);
}});
test('Moving ladders auto-latch, carry horizontally, and allow W/S travel without E',()=>{const{g,p}=setup(0);peaceful(g);const l=geom(g.map.ladders[0],g.mapTime);p.x=l.x+5;p.y=l.y+l.h-95;frame(g,p,INPUT.UP);assert.equal(p.ladder,0);const y=p.y,x=p.x;for(let i=0;i<70;i++)frame(g,p,INPUT.UP);assert.ok(p.y<y-100);assert.ok(Math.abs(p.x-x)>2);const upper=p.y;for(let i=0;i<25;i++)frame(g,p,INPUT.DOWN);assert.ok(p.y>upper+50);frame(g,p,0);assert.equal(p.ladder,0)});
test('All moving/static ladder endpoints support safe ascent and descent',()=>{for(let id=0;id<40;id++){const{g,p}=setup(id);peaceful(g);for(const raw of g.map.ladders){for(const up of [true,false]){const l=geom(raw,g.mapTime);p.x=l.x+8;p.y=up?l.y+l.h-80:l.y+25;p.vy=0;p.ladder=-1;p.ladderBlock=-1;p.ladderLock=0;p.ladderExit=0;p.slide=-1;p.hp=3;let direction=up?INPUT.UP:INPUT.DOWN;for(let i=0;i<200;i++)frame(g,p,direction);frame(g,p,0);for(let i=0;i<90&&!p.grounded;i++)frame(g,p,0);assert.equal(p.hp,3,`ladder damage map ${id}`);assert.ok(p.grounded,`ladder endpoint no landing map ${id} up=${up}`)}}}});
test('Slides land safely and their swept player corridor never intersects another platform, including moving rails',()=>{let total=0;for(let id=0;id<40;id++){const{g,p}=setup(id);peaceful(g);for(const s of g.map.slides){total++;for(const time of [0,.5,2,4,7])for(const state of Object.values(g.movable))state.value=time%1;for(let k=1;k<100;k++){const t=k/100,cx=s.x1+(s.x2-s.x1)*t,feet=s.y1+(s.y2-s.y1)*t;for(const raw of g.map.platforms){if(raw.id===s.from||raw.id===s.to)continue;for(const time of [0,.5,2,4,7]){const pl=platformAt(g,raw.id,time);assert.ok(!(cx+16>pl.x&&cx-16<pl.x+pl.w&&feet>pl.y&&feet-65<pl.y+pl.h),`obstructed slide map ${id} platform ${pl.id}`)}}}
 p.x=s.x1-p.w/2;p.y=s.y1-p.h;p.grounded=true;p.vy=0;const old=p.y;frame(g,p,INPUT.DOWN,INPUT.DOWN);assert.equal(p.slide,s.id);for(let k=0;k<240&&p.slide>=0;k++)frame(g,p);assert.ok(p.y>old+200);assert.equal(p.slide,-1);for(let k=0;k<40&&!p.grounded;k++)frame(g,p);assert.ok(p.grounded,`slide landing ${id}`);assert.equal(p.platform,s.to);
 }}assert.equal(total,6)});
test('Head-riding supports landing, carrying, jumping together, and independent jump-off',()=>{const g=createGame(),base=addPlayer(g,'base','Carrier'),rider=addPlayer(g,'rider','Rider');base.x=500;base.y=650-base.h;base.grounded=true;rider.x=500;rider.y=base.y-18-rider.h-5;rider.vy=200;for(let i=0;i<8;i++)tick(g,{},1/60);assert.equal(rider.riding,base.id);const start=rider.x;for(let i=0;i<45;i++)tick(g,{base:{held:INPUT.RIGHT}},1/60);assert.ok(rider.x>start+120);assert.ok(Math.abs(rider.y+rider.h-(base.y-18))<.1);tick(g,{base:{held:INPUT.JUMP,pressed:INPUT.JUMP}},1/60);assert.equal(rider.riding,base.id);assert.ok(rider.y+rider.h<650-18-base.h);tick(g,{rider:{held:INPUT.JUMP,pressed:INPUT.JUMP}},1/60);assert.equal(rider.riding,null);assert.ok(rider.vy<0)});
test('Revival and team wipe work, and disconnect leaves a solo-completable session',()=>{const{g,p,b}=setup(0,true);peaceful(g);p.x=160;b.x=180;p.y=b.y=g.map.spawn.y;p.inv=0;for(let i=0;i<3;i++){p.inv=0;hurt(g,p,p.x+10)}assert.equal(p.down,true);assert.equal(g.phase,'active');for(let i=0;i<90;i++)tick(g,{bob:{held:INPUT.USE}},1/60);assert.equal(p.down,false);assert.equal(p.hp,2);b.connected=false;objectives(g);exit(g,p);answerBoth(g,p);assert.equal(g.phase,'clear');});
test('Ground NPC contact, projectiles, and hazards cause damage; wrench can defeat bots',()=>{const{g,p}=setup(15);const e=g.enemies.find(e=>e.kind==='walker');p.x=e.x;p.y=e.y;p.inv=0;frame(g,p);assert.equal(p.hp,2);p.inv=0;const b={id:1,x:p.x+16,y:p.y+22,vx:0,life:1};g.bullets.push(b);frame(g,p);assert.equal(p.hp,1);const g2=setup(0);const foe=g2.g.enemies.find(e=>e.kind==='walker');g2.p.x=foe.x-35;g2.p.y=foe.y;g2.p.face=1;frame(g2.g,g2.p,0,INPUT.ATTACK);assert.ok(foe.dead)});
test('Every authored jump and automatic ladder landing has a solo trajectory under the actual physics',()=>{
 let transitions=0;const failures=[];
 for(let id=0;id<40;id++){const{g,p}=setup(id);peaceful(g);g.map.fuses=[];g.map.meds=[];g.map.slides=[];
  for(const edge of g.map.route.filter(e=>e.kind==='J'||e.kind==='G'||e.kind==='K')){
   if(edge.kind==='G')g.movable[edge.from].value=1;
   let solved=false;
   for(const phase of [0,1.5]){for(const delay of [.17,.27,.38,.48,.58,0,-1,-2]){
    g.mapTime=phase;const a=platformAt(g,edge.from),b=platformAt(g,edge.to),dir=Math.sign(b.x+b.w/2-a.x-a.w/2)||1;
    Object.assign(p,{x:dir>0?a.x+a.w-42:a.x+10,y:a.y-p.h,vx:dir*295,vy:0,hp:3,down:false,grounded:true,platform:a.id,jumps:0,ladder:-1,ladderBlock:-1,ladderExit:0,ladderLock:0,slide:-1,grab:-1,riding:null,inv:0,drop:0,coyote:0,launchLock:0,launchCD:0});g.phase='active';let second=false;const launch=['spring','launcher'].includes(a.type);if(launch)frame(g,p);
    for(let k=0;k<170;k++){let press=k===0&&!launch&&delay>=0?INPUT.JUMP:k===0&&delay===-2?INPUT.DOWN:0;if(delay>0&&!second&&k/60>=delay){press|=INPUT.JUMP;second=true}const dest=platformAt(g,edge.to),target=dest.x+dest.w*.5-p.w/2,delta=target-p.x;const move=Math.abs(delta)>9?(delta>0?INPUT.RIGHT:INPUT.LEFT):0;let held=(delay>=0?INPUT.JUMP:0)|move;if(p.ladder>=0){const l=geom(g.map.ladders[p.ladder],g.mapTime);held=Math.abs(dest.y-l.y)<Math.abs(dest.y-l.y-l.h)?INPUT.UP:INPUT.DOWN;press=0;}frame(g,p,held,press);
     if((p.landed===edge.to||p.grounded&&p.platform===edge.to)||(dest.type==='fan'&&p.x+p.w>dest.x&&p.x<dest.x+dest.w&&p.y+p.h<dest.y&&p.y+p.h>dest.y-200)){solved=true;break;}if(p.down||p.hp<3)break;
    }if(solved)break;
   }if(solved)break;}
   if(!solved)failures.push(`${id}: ${edge.from}->${edge.to} (${edge.kind})`);transitions++;
  }
 }
 assert.deepEqual(failures,[]);assert.ok(transitions>350);console.log('Verified solo jump and dock transitions:',transitions);
});
test('Restart door requires confirmation action and cannot reset an online session',()=>{const g=createGame(25),p=addPlayer(g,'solo','Custom',{color:'#f493b0'});assert.equal(command(g,p,'restartCampaign'),false);p.x=390;interact(g,p);assert.equal(p.interaction,'restart');assert.equal(g.progress,25);command(g,p,'close');assert.equal(g.progress,25);interact(g,p);assert.equal(command(g,p,'restartCampaign'),true);assert.equal(g.progress,0);assert.equal(p.name,'Custom');assert.equal(p.avatar.color,normalizeAvatar().color);assert.equal(g.mode,'lobby');p.x=doorX(1)+65;interact(g,p);assert.equal(p.interaction,null);const net=createGame(25,true),n=addPlayer(net,'n','Net');n.x=390;interact(net,n);assert.notEqual(n.interaction,'restart');n.interaction='restart';assert.equal(command(net,n,'restartCampaign'),false);assert.equal(net.progress,25)});
test('All grab carriages move only while E is held, carry riders, release, and synchronize',()=>{let total=0;for(let id=0;id<40;id++){const{g,p,b}=setup(id,true);peaceful(g);for(const raw of g.map.platforms.filter(p=>p.track)){total++;g.mapTime=0;g.movable[raw.id].value=0;Object.assign(p,{x:raw.x+20,y:raw.y-p.h,grounded:true,platform:raw.id,vx:0,vy:0,ladder:-1,slide:-1,riding:null});Object.assign(b,{x:raw.x+75,y:raw.y-b.h,grounded:true,platform:raw.id,vx:0,vy:0,ladder:-1,slide:-1,riding:null});const start=p.x,startB=b.x,dir=raw.track.x>0?INPUT.RIGHT:INPUT.LEFT;
 for(let k=0;k<140;k++)tick(g,{alice:{held:INPUT.USE|dir}},1/60);assert.equal(g.movable[raw.id].value,1);assert.ok(Math.abs(p.x-start-raw.track.x)<3);assert.ok(Math.abs(b.x-startB-raw.track.x)<3);assert.equal(g.movable[raw.id].owner,'alice');const clone=restoreSnapshot(structuredClone(snapshot(g)));assert.equal(platformAt(clone,raw.id).x,platformAt(g,raw.id).x);frame(g,p);assert.equal(g.movable[raw.id].owner,null);frame(g,p,INPUT.JUMP,INPUT.JUMP);assert.ok(p.vy<0);assert.equal(p.grab,-1);assert.equal(g.movable[raw.id].value,1);
 const call=platformAt(g,raw.track.call);Object.assign(p,{x:call.x+call.w*.7-16,y:call.y-p.h,grounded:true,platform:call.id,vx:0,vy:0});frame(g,p,INPUT.USE,INPUT.USE);for(let k=0;k<140;k++)frame(g,p);assert.equal(g.movable[raw.id].value,0,'carriage can be recalled after a fall or quiz teleport');
 }}assert.ok(total>=12)});
test('Laser tracking telegraphs, locks, damages only during firing and is stopped by platforms',()=>{const{g,p}=setup(10);g.map.hazards=[];g.relays.forEach(r=>r.open=true);const e=g.enemies.find(e=>e.kind==='laser');g.enemies=[e];const floor=g.map.platforms[e.platform];floor.w=650;floor.x=e.x-250;Object.assign(p,{x:e.x+130,y:floor.y-p.h,grounded:true,platform:floor.id,inv:0});let aim=false,lock=false,fire=false,lockedAngle;for(let i=0;i<180;i++){frame(g,p);if(e.beamState==='aim'){aim=true;assert.equal(p.hp,3)}if(e.beamState==='lock'){lock=true;if(lockedAngle===undefined)lockedAngle=e.angle;else assert.equal(e.angle,lockedAngle);assert.equal(p.hp,3)}if(e.beamState==='fire'){fire=true;break}}assert.ok(aim&&lock&&fire);assert.equal(p.hp,2);const beam=beamFor(g,e);assert.ok(rayBox(beam.x,beam.y,beam.dx,beam.dy,p,beam.length)<beam.length);const cover={id:g.map.platforms.length,x:e.x+65,y:e.y-100,w:20,h:200,type:'normal'};g.map.platforms.push(cover);p.hp=3;p.inv=0;frame(g,p);assert.equal(p.hp,3);assert.ok(beamFor(g,e).length<100);});
