import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,addPlayer,startMap,enterLobby,tick,INPUT,command,interact,platformAt,solidWalls,snapshot,restoreSnapshot,startStory,normalizeAccount} from '../public/core.js';
import {traceOptics} from '../public/optics.js';
import {STORY,StoryVoice} from '../public/story.js';
import {HEADS} from '../public/data.js';
const step=(g,p,held=0,pressed=0)=>tick(g,{[p.id]:{held,pressed}},1/60);
function setup(id,two=false){const g=createGame(40),p=addPlayer(g,'a','Alice');if(two)addPlayer(g,'b','Bob');startMap(g,id);g.enemies=[];return{g,p,b:g.players[1]};}
function place(g,p,id,x){const pl=platformAt(g,id);Object.assign(p,{x:x??pl.x+pl.w/2-16,y:pl.y-p.h,vx:0,vy:0,grounded:true,platform:id,ladder:-1,slide:-1,down:false,hp:3,launchCD:0,launchLock:0});return pl;}
test('Every optical puzzle requires both reflections; E dragging solves and latches its actual gate',()=>{let count=0;for(let id=0;id<40;id++){const{g,p}=setup(id);g.map.hazards=[];for(const def of g.map.optics){count++;const state=g.optics[def.id];assert.equal(traceOptics(def,state).lit,false);assert.ok(solidWalls(g).some(w=>w.kind==='mirror'));place(g,p,def.platform,def.x-16);for(let k=0;k<68;k++)step(g,p,INPUT.USE|INPUT.RIGHT,k===0?INPUT.USE:0);assert.ok(state.x>def.min+110&&state.x<def.min+125);const trace=traceOptics(def,state);assert.equal(trace.lit,true);assert.equal(trace.hit.length,2);assert.equal(trace.segments.length,3);for(let k=0;k<42;k++)step(g,p,INPUT.USE);assert.equal(state.solved,true);assert.ok(!solidWalls(g).some(w=>w.kind==='mirror'));const client=restoreSnapshot(structuredClone(snapshot(g)));assert.equal(client.optics[0].solved,true);assert.equal(client.optics[0].x,state.x);}}assert.equal(count,8)});
test('Fast conveyors move an idle player toward a real spike/saw hazard; jumping can clear it',()=>{let n=0,types=new Set();for(let id=0;id<40;id++){const{g,p}=setup(id);const hazards=[...g.map.hazards];for(const pl of g.map.platforms.filter(p=>p.type==='conveyor')){n++;g.map.hazards=hazards.filter(h=>h.platform===pl.id);const h=g.map.hazards.find(h=>['saw','spikes'].includes(h.type));assert.ok(h);types.add(h.type);const from=pl.conveyor>0?pl.x+45:pl.x+pl.w-80;place(g,p,pl.id,from);p.inv=0;const x=p.x;for(let i=0;i<15;i++)step(g,p);assert.ok(Math.abs(p.x-x)>55);for(let i=0;i<50&&p.hp===3;i++)step(g,p);assert.ok(p.hp<3,'belt hazard damages map '+id);place(g,p,pl.id,from);p.inv=0;for(let i=0;i<8;i++)step(g,p);const before=p.hp;step(g,p,INPUT.JUMP,INPUT.JUMP);assert.ok(p.vy<0);for(let i=0;i<12;i++)step(g,p,INPUT.JUMP);assert.equal(p.hp,before);}}assert.ok(n>=14);assert.deepEqual([...types].sort(),['saw','spikes'])});
test('Spring blocks launch upward and directional blocks produce sustained horizontal travel',()=>{let springs=0,launchers=0;for(let id=0;id<40;id++){const{g,p}=setup(id);g.map.hazards=[];g.optics.forEach(o=>o.solved=true);g.routeProgress=g.map.platforms.length-1;for(const pl of g.map.platforms.filter(p=>p.type==='spring'||p.type==='launcher')){place(g,p,pl.id);const x=p.x,y=p.y;step(g,p);assert.ok(p.vy<-750);assert.equal(p.grounded,false);assert.equal(p.landed,pl.id);if(pl.type==='spring'){springs++;step(g,p,INPUT.JUMP);}else{launchers++;assert.ok(Math.abs(p.vx)>600);for(let k=0;k<25;k++)step(g,p,INPUT.JUMP);assert.ok(Math.abs(p.x-x)>250);}assert.ok(p.y<y);}}assert.ok(springs>=4);assert.equal(launchers,6)});
test('Skipping to the exit cannot clear a map: ordered route beacons and a physical bulkhead enforce the path',()=>{for(let id=0;id<40;id++){const{g,p}=setup(id);g.map.hazards=[];g.fuses.fill(true);g.relays.forEach(r=>r.open=true);g.optics.forEach(o=>o.solved=true);const last=g.map.platforms.length-1;place(g,p,last);interact(g,p);assert.equal(p.quiz,null);assert.ok(solidWalls(g).some(w=>w.kind==='route'));for(let i=1;i<last;i++){place(g,p,i);step(g,p);assert.equal(g.routeProgress,i,`ordered landing ${id}/${i}`);}assert.ok(!solidWalls(g).some(w=>w.kind==='route'));place(g,p,last);step(g,p);assert.equal(g.routeProgress,last);interact(g,p);assert.ok(p.quiz);}});
test('Structural path blocks stop downward and upward passage',()=>{const{g,p}=setup(11);g.map.hazards=[];g.map.platforms=[];g.map.relays=[];g.relays=[];g.map.optics=[];g.optics=[];g.map.fuses=[];g.fuses=[];g.map.meds=[];g.map.ladders=[];g.map.slides=[];g.map.barriers=[{x:400,y:650,w:240,h:34}];g.routeProgress=0;Object.assign(p,{x:480,y:590,vy:250,vx:0,grounded:false});for(let i=0;i<10;i++)step(g,p);assert.equal(p.y+p.h,650);Object.assign(p,{x:480,y:700,vy:-500,grounded:false,launchCD:1});step(g,p,INPUT.JUMP);step(g,p,INPUT.JUMP);step(g,p,INPUT.JUMP);assert.ok(p.y>=684);assert.ok(p.vy>=0);});
test('Each new fuse gives both players points once, retries preserve purchases, and a fresh campaign resets cosmetics',()=>{const{g,p,b}=setup(0,true);g.map.hazards=[];const f=g.map.fuses[0],pl=platformAt(g,f.platform);Object.assign(p,{x:pl.x+f.offset-16,y:pl.y-f.yoff-20,vx:0,vy:0});step(g,p);assert.equal(p.wallet,10);assert.equal(b.wallet,10);assert.deepEqual(p.claimed,['0:0']);startMap(g,0);g.enemies=[];g.map.hazards=[];Object.assign(p,{x:pl.x+f.offset-16,y:pl.y-f.yoff-20});step(g,p);assert.equal(p.wallet,10);enterLobby(g);p.x=190;interact(g,p);assert.equal(command(g,p,'buyHead',{head:'screen'}),false);p.wallet=500;assert.equal(command(g,p,'buyHead',{head:'screen'}),true);assert.equal(p.wallet,400);assert.equal(command(g,p,'buyHead',{head:'screen'}),false);assert.equal(p.wallet,400);assert.equal(command(g,p,'avatar',{avatar:{shape:'cat'}}),false);assert.equal(command(g,p,'avatar',{avatar:{shape:'screen'},name:'Monitor'}),true);b.connected=false;command(g,p,'close');p.x=390;interact(g,p);assert.equal(command(g,p,'restartCampaign'),true);assert.equal(p.wallet,0);assert.deepEqual(p.heads,['square','round','point']);assert.deepEqual(p.claimed,[]);const fresh=createGame(),copy=addPlayer(fresh,'fresh',p.name,p.avatar,normalizeAccount(p));assert.equal(copy.wallet,0);assert.equal(copy.avatar.shape,'square');startMap(g,0);g.enemies=[];g.map.hazards=[];Object.assign(p,{x:pl.x+f.offset-16,y:pl.y-f.yoff-20});step(g,p);assert.equal(p.wallet,10,'a fresh campaign can earn its fuses again');assert.ok(HEADS.filter(h=>h.price).reduce((n,h)=>n+h.price,0)<=120*10);});
test('Nine chapters advance, freeze gameplay, wait for finale confirmation, and return through the correct door',()=>{assert.equal(STORY.length,9);for(let chapter=0;chapter<9;chapter++){const{g,p}=setup(Math.max(0,chapter*5-1));const room=Math.max(0,chapter-1);startStory(g,chapter,{kind:chapter===0?'level':'lobby',level:0,room});const x=p.x,y=p.y;step(g,p,INPUT.RIGHT|INPUT.JUMP,INPUT.JUMP);assert.equal(p.x,x);assert.equal(p.y,y);assert.equal(g.story.playing,true);assert.ok(g.story.elapsed>0,'chapter starts without a play command');assert.equal(command(g,p,'retry'),false);assert.equal(command(g,p,'storyPlay',{},false),false);const elapsed=g.story.elapsed;command(g,p,'storyPause');tick(g,{},1);assert.equal(g.story.elapsed,elapsed);command(g,p,'storyPause');let confirms=0;for(let guard=0;g.story&&guard<40;guard++){const s=g.story,b=STORY[chapter].beats[s.beat];command(g,p,'storySpeechStart',{storyId:s.id,chapter,beat:s.beat,take:0});command(g,p,'storySpeechDone',{storyId:s.id,chapter,beat:s.beat,take:0});tick(g,{},b.duration+.1);if(g.story?.waiting){if(b.confirm){confirms++;assert.equal(chapter,8);const beat=s.beat;tick(g,{},100);assert.equal(g.story.beat,beat);}command(g,p,'storyAdvance');}}assert.equal(g.story,null);assert.equal(confirms,chapter===8?1:0);if(chapter===0){assert.equal(g.level,0);assert.equal(g.seenOpening,true);}else{assert.equal(g.mode,'lobby');assert.equal(g.returnRoom,room);}}});
test('Narration speaks each caption once, switches speaker settings and can be muted',()=>{const spoken=[];let cancelled=0;const old=globalThis.window;globalThis.window={speechSynthesis:{cancel(){cancelled++},getVoices(){return[{lang:'en-US',name:'A'},{lang:'en-US',name:'B'},{lang:'en-GB',name:'C'}]},speak(u){spoken.push(u)}},SpeechSynthesisUtterance:class{constructor(text){this.text=text}}};try{const voice=new StoryVoice(),s={chapter:0,beat:0,playing:true,paused:false};assert.ok(voice.available);voice.update(s);voice.update(s);assert.equal(spoken.length,1);assert.equal(spoken[0].text,STORY[0].beats[0].text);s.beat=1;voice.update(s);assert.equal(spoken.length,2);assert.notEqual(spoken[0].pitch,spoken[1].pitch);voice.enabled=false;voice.update(s);assert.ok(cancelled>1);assert.equal(spoken.length,2);}finally{globalThis.window=old;}});
test('Every relay pad is on a standable surface; all stations work with two players',()=>{for(let id=0;id<40;id++){const{g,p,b}=setup(id,true);g.map.hazards=[];g.optics.forEach(o=>o.solved=true);g.routeProgress=g.map.platforms.length-1;for(let i=0;i<g.map.relays.length;i++){const relay=g.map.relays[i];relay.plates.forEach((plate,j)=>{const pl=platformAt(g,plate.platform);assert.ok(!['spring','launcher','fan','conveyor'].includes(pl.type));place(g,j?b:p,pl.id,pl.x+plate.offset-16);});for(let k=0;k<38;k++)tick(g,{},1/60);assert.equal(g.relays[i].open,true,`relay ${id}/${i}`);}}});
test('Two crew members cannot move the same optical block twice in one tick',()=>{const{g,p,b}=setup(4,true),def=g.map.optics[0];g.map.hazards=[];place(g,p,def.platform,def.x-16);place(g,b,def.platform,def.x-16);tick(g,{a:{held:INPUT.USE|INPUT.RIGHT},b:{held:INPUT.USE|INPUT.LEFT}},1/60);assert.equal(g.optics[0].owner,'a');assert.equal(g.optics[0].x,def.min+105/60);tick(g,{b:{held:INPUT.USE|INPUT.LEFT}},1/60);assert.equal(g.optics[0].owner,'b');assert.equal(g.optics[0].x,def.min);});
